### ISSUE TITLE
Version preview exception

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-backend-bundle#267] opened 2024-07-18 09:44 UTC
When I create a version e.g. for Asset ID 254 of the demo-enterprise and then call the versions preview endpoint the following exception appears:

![image](https://github.com/user-attachments/assets/e5535436-f217-4d4d-a1c9-6f0a9aee9d31)

I guess this happens because of the asset metadata:

![image](https://github.com/user-attachments/assets/053c3df7-c207-417f-9413-95020328cf86)

There we have linked cars - can they be the reason that the serialization fails?

**Comment by lukmzig** [comment] 2024-07-22 13:02
@markus-moser should be fixed now, it was indeed caused by multi-relational field in the meta data

**Closed as completed** 2024-07-22 13:01 UTC
Labels: Bug

**Comment by markus-moser** [comment] 2024-07-22 16:01
@lukmzig Confirmed - it works as expected now 👍
